### ISSUE TITLE
Crashed while hitting a cow.

### ISSUE THREAD

**Issue by harleyofallthings** [arthurbambou/Randomly-Adding-Anything#105]
Edit: Further testing, hitting an entity with any item that was from randomly generated ores seems to crash the game, not just cows. Normal materials work fine. 

Edit 2: I was actually on 0.1.7 instead of 0.1.9, I'm testing the newer version. 

I don't know what happened, but I hit a cow with a randomized sword and it crashed. 
OS: Windows (but I use macos bootcamp to run windows)
crash report:
---- Minecraft Crash Report ----
// On the bright side, I bought you a teddy bear!

Time: 7/23/20 7:45 AM
Description: Ticking entity

java.lang.NullPointerException: Ticking entity
	at net.minecraft.class_1293.method_5585(class_1293.java:147)
	at net.minecraft.class_1309.method_6050(class_1309.java:725)
	at net.minecraft.class_1309.method_5670(class_1309.java:410)
	at net.minecraft.class_1308.method_5670(class_1308.java:271)
	at net.minecraft.class_1297.method_5773(class_1297.java:422)
	at net.minecraft.class_1309.method_5773(class_1309.java:2206)
	at net.minecraft.class_1308.method_5773(class_1308.java:338)
	at net.minecraft.class_3218.method_18762(class_3218.java:615)
	at net.minecraft.class_3218$$Lambda$4729/510379740.accept(Unknown Source)
	at net.minecraft.class_1937.method_18472(class_1937.java:603)
	at net.minecraft.class_3218.method_18765(class_3218.java:405)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:873)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:813)
	at net.minecraft.class_1132.method_3748(class_1132.java:93)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:672)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:256)
	at net.minecraft.server.MinecraftServer$$Lambda$4244/1007076085.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.class_1293.method_5585(class_1293.java:147)
	at net.minecraft.class_1309.method_6050(class_1309.java:725)
	at net.minecraft.class_1309.method_5670(class_1309.java:410)
	at net.minecraft.class_1308.method_5670(class_1308.java:271)
	at net.minecraft.class_1297.method_5773(class_1297.java:422)
	at net.minecraft.class_1309.method_5773(class_1309.java:2206)
	at net.minecraft.class_1308.method_5773(class_1308.java:338)
	at net.minecraft.class_3218.method_18762(class_3218.java:615)
	at net.minecraft.class_3218$$Lambda$4729/510379740.accept(Unknown Source)

-- Entity being ticked --
Details:
	Entity Type: minecraft:cow (net.minecraft.class_1430)
	Entity ID: 3342
	Entity Name: Cow
	Entity's Exact location: 362.88, 64.00, 159.12
	Entity's Block location: World: (362,64,159), Chunk: (at 10,4,15 in 22,9; contains blocks 352,0,144 to 367,255,159), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Entity's Momentum: 0.70, 0.40, -0.01
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.class_1937.method_18472(class_1937.java:603)
	at net.minecraft.class_3218.method_18765(class_3218.java:405)

-- Affected level --
Details:
	All players: 1 total; [class_3222['DogMaster6'/890, l='ServerLevel[New World]', x=360.29, y=64.00, z=159.22]]
	Chunk stats: ServerChunkCache: 2845
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,70,112), Chunk: (at 0,4,0 in 0,7; contains blocks 0,0,112 to 15,255,127), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 11153 game time, 11153 day time
	Level name: New World
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
	Level weather: Rain time: 30773 (now: false), thunder time: 96038 (now: false)
	Known server brands: fabric
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:873)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:813)
	at net.minecraft.class_1132.method_3748(class_1132.java:93)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:672)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:256)
	at net.minecraft.server.MinecraftServer$$Lambda$4244/1007076085.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.16.1
	Minecraft Version ID: 1.16.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 750732976 bytes (715 MB) / 2147483648 bytes (2048 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 16
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		artifice: Artifice 0.8.0+1.16-rc1
		autoconfig1u: Auto Config v1 Updated 3.0.0-unstable
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-config2: Cloth Config v2 4.4.1-unstable
		fabric: Fabric API 0.15.1+build.380-1.16.1
		fabric-api-base: Fabric API Base 0.1.3+12a8474c02
		fabric-biomes-v1: Fabric Biomes (v1) 0.2.7+059ea86602
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.4+c6a8ea8902
		fabric-command-api-v1: Fabric Command API (v1) 1.0.8+5ce5339802
		fabric-commands-v0: Fabric Commands (v0) 0.2.0+52d3083602
		fabric-containers-v0: Fabric Containers (v0) 0.1.8+045df74f02
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.1.9+059ea86602
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.2+b7f9825d02
		fabric-dimensions-v1: fabric-dimensions-v1 1.0.0+a71b305302
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.3.3+7066030f02
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.0+16acbe5b02
		fabric-item-api-v1: Fabric Item API (v1) 1.0.0+16acbe5b02
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.0+438f963602
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.1+f404f3be02
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.0+3fa9f7c502
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.1.0+013e49d202
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.0+386eb69e02
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.2+b764ce9902
		fabric-models-v0: Fabric Models (v0) 0.1.0+dfdb52d602
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.5+b50ffc7b02
		fabric-networking-v0: Fabric Networking (v0) 0.1.10+e00ecb5f02
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.5.6+a2d21ddd02
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.6.1+a2d21ddd02
		fabric-particles-v1: fabric-particles-v1 0.2.1+0a6f2a7002
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.3.8+7dba2d6c02
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.2.13+eae12eb802
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.3.3+0a55f37902
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.0.1+5a0f9a6002
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.3+b7f9825d02
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.8+b7084faa02
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.0+5341049002
		fabric-rendering-v1: Fabric Rendering (v1) 1.1.2+346247d702
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.2.6+f41e209802
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.0+97324d1102
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 0.2.7+a4c57d8e02
		fabric-textures-v0: Fabric Textures (v0) 1.0.4+eae12eb802
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.1.4+5794386e02
		fabricloader: Fabric Loader 0.9.0+build.204
		jankson: Jankson 2.0.1+j1.2.0
		minecraft: Minecraft 1.16.1
		raa_core: RAA: Core 0.1.7+1.16.1
		raa_materials: RAA: Materials 0.1.3
		vampirelib: VampireLib 1.8.0+build.1-1.16.1
	Player Count: 1 / 8; [class_3222['DogMaster6'/890, l='ServerLevel[New World]', x=360.29, y=64.00, z=159.22]]
	Data Packs: vanilla, fabric/fabric-tool-attribute-api-v1, fabric/vampirelib, raa_materials:recipe_pack_1
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fabric'

**Comment by harleyofallthings** [comment]
I'd like to also mention that this happens repeatedly, not just once. but only when I hit a cow, I'm testing on other animals.

**Comment by ValkWetenschap** [comment]
This happens to me as well, which really sucks because I love the idea of the mod. Does anyone know how to fix it? Does it happen with all versions of the mod, or just a couple?
