### ISSUE TITLE
Cannot find required mod

### ISSUE THREAD

**Issue by HotPizzaYT** [arthurbambou/Randomly-Adding-Anything#69]
`A critical error occurred
net.fabricmc.loader.discovery.ModResolutionException: Could not find required mod: raa requires {fabric @ [*]}
	at net.fabricmc.loader.discovery.ModResolver.findCompatibleSet(ModResolver.java:169)
	at net.fabricmc.loader.discovery.ModResolver.resolve(ModResolver.java:602)
	at net.fabricmc.loader.FabricLoader.setup(FabricLoader.java:176)
	at net.fabricmc.loader.FabricLoader.load(FabricLoader.java:166)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:127)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
Caused by: net.fabricmc.loader.util.sat4j.specs.ContradictionException: Creating Empty clause ?
	at net.fabricmc.loader.util.sat4j.minisat.constraints.cnf.Clauses.propagationCheck(Clauses.java:117)
	at net.fabricmc.loader.util.sat4j.minisat.constraints.cnf.Clauses.sanityCheck(Clauses.java:97)
	at net.fabricmc.loader.util.sat4j.minisat.constraints.MixedDataStructureDanielWL.createClause(MixedDataStructureDanielWL.java:81)
	at net.fabricmc.loader.util.sat4j.minisat.core.Solver.addClause(Solver.java:401)
	at net.fabricmc.loader.discovery.ModResolver.findCompatibleSet(ModResolver.java:167)
	... 5 more`

**Comment by ghost** [comment]
You need [Fabric API](https://www.curseforge.com/minecraft/mc-mods/fabric-api) as well (and that's the case for most Fabric mods).
